language: node_js
node_js: "10"
deploy:
  provider: heroku
  api_key:
    secure: f7IsbVYHTs7SIqBgWN8Lb8+FEVt8GyepbyfGvHVP9OtatZ2h8tfcIH6Yn/DxNbEYEkaqWaNQCF0YFflT2Dd5hzBy96UreDPaVxt0jyGL7WBYvc4e//66ieOYimNAirfA7Vzzf5fxYy8r5CpVDWGHwsDBYy+nsrccWV0PpbX27tviZVzyjdi2ZSSeFYB8oAURuKSbCmOQhMUSy9PSI6Ih65ZBVUOUFLiWEvGJnR/SiebYMKPPNadzkW1cqp1RdKOcJx7A/y81lqPH0yu9E0sD20SVQDVBP7OSPN/BiRA11mqfodtaZgb6U5hsQrI4mWlL7s7e2AuQWgjs6VJ6lofo6uB0xwCGzoeTIqp7uiwAaV9a9YIV+l1U58HHpy7DoABl0ySzuaJOun32iyvT+MwW0oMD4uETFHq9z0SaGNBcjG3rq3Ph9g5rYalBYPbSqMXrfOvw27tchCy+ulZ3EqouFjcIa6MBmEMIgsY9NHBBSCglFWkRHw2suguuwH6TnMFeiax+XSocULiJH84SqTACVlqi4qW3GUdIoHDDmfUNAiRdLp0fOmNfxtBklGpbhDzrAhXv1EOGxKXFACNC7XJvFTjOmL2X+NzU/wJj8cn38phV1adRmyQ5Kp5Nmx26XnqZoWvABZO48C38ED65zZi5x/YXa430ttbLNoGOe3Q/HCg=
branches:
  only:
  - master